include:

  ### SOFLEV2 SOFLEV1 SOFLEPLUS START ###
  # nice!oled sofle
  # - board: nice_nano_v2
  #   shield: sofle_left nice_oled
  #   cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Sofle_Oled\"  -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SLEEP=y -DCONFIG_ZMK_IDLE_TIMEOUT=60000
  #   artifact-name: nice_sofle_left_oled
  #   snippet: studio-rpc-usb-uart

  - board: nice_nano_v2
    shield: sofle_right nice_oled
    cmake-args: -DCONFIG_ZMK_SLEEP=y -DCONFIG_ZMK_IDLE_TIMEOUT=60000
    artifact-name: nice_sofle_right_oled
    snippet: zmk-usb-logging

  # peripheral_left
  - board: nice_nano_v2
    shield: sofle_left_peripheral nice_oled
    cmake-args: -DCONFIG_ZMK_SLEEP=y -DCONFIG_ZMK_IDLE_TIMEOUT=60000
    artifact-name: nice_sofle_left_peripheral_oled
    snippet: zmk-usb-logging

  # ProMicro_Dongle
  - board: nice_nano_v2
    shield: sofle_dongle_pro_micro dongle_display
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"SofleDongle_P\"  -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SLEEP=n -DCONFIG_ZMK_IDLE_TIMEOUT=60000
    artifact-name: nice_sofle_dongle_oled
    snippet: zmk-usb-logging
  ### SOFLEV2 SOFLEV1 SOFLEPLUS END ###

  ### SETTINGS_RESET START ###
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: nice_settings_reset
  ### SETTINGS_RESET END ###
