include:

  - board: nice_nano_v2
    shield: sofle_right nice_oled
    artifact-name: sofle_right 

  # peripheral_left
  - board: nice_nano_v2
    shield: sofle_left_peripheral nice_oled
    artifact-name: sofle_left

  # ProMicro_Dongle
  - board: nice_nano_v2
    shield: sofle_dongle_pro_micro dongle_display
    artifact-name: sofle_dongle
  ### SOFLEV2 SOFLEV1 SOFLEPLUS END ###

  ### SETTINGS_RESET START ###
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: settings_reset
  ### SETTINGS_RESET END ###
